import prisma from '../../config/database';
import {
  Account,
  CreateAccountDto,
  UpdateAccountDto,
  AccountFilters,
  AccountTreeResponse,
  AccountBalanceResponse,
} from './types';
import { AccountType } from '@prisma/client';

export class AccountService {
  /**
   * Create a new account
   * Validates that parent account exists and prevents circular references
   */
  async createAccount(tenantId: string, data: CreateAccountDto): Promise<Account> {
    // Check if account code already exists in this tenant
    const existingAccount = await prisma.account.findFirst({
      where: { tenantId, code: data.code },
    });

    if (existingAccount) {
      throw new Error('Account with this code already exists');
    }

    // If parent is provided, validate it exists and belongs to tenant
    if (data.parentId) {
      const parentAccount = await prisma.account.findFirst({
        where: { id: data.parentId, tenantId },
      });

      if (!parentAccount) {
        throw new Error('Parent account not found');
      }

      // Circular reference check for createAccount:
      // In createAccount, the account doesn't have an ID yet (generated by Prisma),
      // so circular reference is not possible here.
      // The real circular reference check is done in updateAccount with isDescendant().
    }

    const account = await prisma.account.create({
      data: {
        tenantId,
        code: data.code,
        nameAr: data.nameAr,
        nameEn: data.nameEn || data.nameAr,
        parentId: data.parentId || null,
        accountType: data.accountType,
        isActive: data.isActive ?? true,
        balanceSYP: data.balanceSYP ?? 0,
        balanceUSD: data.balanceUSD ?? 0,
      },
    });

    return this.mapToAccountResponse(account);
  }

  /**
   * Get all accounts with optional filters
   */
  async getAccounts(
    tenantId: string,
    filters: AccountFilters = {}
  ): Promise<Account[]> {
    const where: any = { tenantId };

    if (filters.accountType) {
      where.accountType = filters.accountType;
    }
    if (filters.parentId !== undefined) {
      where.parentId = filters.parentId;
    }
    if (filters.isActive !== undefined) {
      where.isActive = filters.isActive;
    }
    if (filters.search) {
      where.OR = [
        { nameAr: { contains: filters.search, mode: 'insensitive' } },
        { nameEn: { contains: filters.search, mode: 'insensitive' } },
        { code: { contains: filters.search, mode: 'insensitive' } },
      ];
    }

    const accounts = await prisma.account.findMany({
      where,
      orderBy: [{ code: 'asc' }],
    });

    return accounts.map((acc) => this.mapToAccountResponse(acc));
  }

  /**
   * Get account by ID
   */
  async getAccountById(tenantId: string, accountId: string): Promise<Account | null> {
    const account = await prisma.account.findFirst({
      where: { id: accountId, tenantId },
      include: {
        parent: true,
        children: true,
      },
    });

    if (!account) {
      return null;
    }

    return this.mapToAccountResponse(account);
  }

  /**
   * Update account
   * Prevents changing parent to create circular references
   */
  async updateAccount(
    tenantId: string,
    accountId: string,
    data: UpdateAccountDto
  ): Promise<Account> {
    // Check if account exists
    const existingAccount = await prisma.account.findFirst({
      where: { id: accountId, tenantId },
    });

    if (!existingAccount) {
      throw new Error('Account not found');
    }

    // If updating code, check for duplicates
    if (data.code && data.code !== existingAccount.code) {
      const duplicateCode = await prisma.account.findFirst({
        where: { tenantId, code: data.code, id: { not: accountId } },
      });

      if (duplicateCode) {
        throw new Error('Account with this code already exists');
      }
    }

    // If updating parent, validate and check for circular reference
    if (data.parentId !== undefined) {
      if (data.parentId === accountId) {
        throw new Error('Cannot set account as its own parent');
      }

      if (data.parentId) {
        const parentAccount = await prisma.account.findFirst({
          where: { id: data.parentId, tenantId },
        });

        if (!parentAccount) {
          throw new Error('Parent account not found');
        }

        // Check if the new parent is a descendant of this account (circular reference)
        const isDescendant = await this.isDescendant(accountId, data.parentId);
        if (isDescendant) {
          throw new Error('Circular reference detected: cannot move account under its descendant');
        }
      }
    }

    const updateData: any = {
      ...(data.code && { code: data.code }),
      ...(data.nameAr && { nameAr: data.nameAr }),
      ...(data.nameEn && { nameEn: data.nameEn }),
      ...(data.parentId !== undefined && { parentId: data.parentId }),
      ...(data.accountType && { accountType: data.accountType }),
      ...(data.isActive !== undefined && { isActive: data.isActive }),
    };

    if (data.balanceSYP !== undefined) {
      updateData.balanceSYP = data.balanceSYP;
    }
    if (data.balanceUSD !== undefined) {
      updateData.balanceUSD = data.balanceUSD;
    }

    const updatedAccount = await prisma.account.update({
      where: { id: accountId },
      data: updateData,
    });

    return this.mapToAccountResponse(updatedAccount);
  }

  /**
   * Delete account (soft delete by deactivating)
   */
  async deleteAccount(tenantId: string, accountId: string): Promise<void> {
    const account = await prisma.account.findFirst({
      where: { id: accountId, tenantId },
      include: { children: true },
    });

    if (!account) {
      throw new Error('Account not found');
    }

    // Check if account has children
    if (account.children.length > 0) {
      throw new Error('Cannot delete account with child accounts. Delete children first.');
    }

    // Check if account has journal lines
    const journalLinesCount = await prisma.journalLine.count({
      where: { accountId },
    });

    if (journalLinesCount > 0) {
      throw new Error('Cannot delete account with journal entries. Deactivate instead.');
    }

    await prisma.account.update({
      where: { id: accountId },
      data: { isActive: false },
    });
  }

  /**
   * Get account tree (hierarchical structure)
   */
  async getAccountTree(tenantId: string): Promise<AccountTreeResponse[]> {
    const accounts = await prisma.account.findMany({
      where: { tenantId, isActive: true },
      orderBy: [{ code: 'asc' }],
    });

    // Build tree structure
    const accountMap = new Map<string, AccountTreeResponse>();
    const rootAccounts: AccountTreeResponse[] = [];

    // First pass: create all nodes
    accounts.forEach((acc) => {
      accountMap.set(acc.id, {
        id: acc.id,
        code: acc.code,
        name: acc.nameEn,
        nameAr: acc.nameAr,
        accountType: acc.accountType,
        balanceSYP: Number(acc.balanceSYP),
        balanceUSD: Number(acc.balanceUSD),
        isActive: acc.isActive,
        children: [],
        level: 0,
      });
    });

    // Second pass: build hierarchy
    accounts.forEach((acc) => {
      const node = accountMap.get(acc.id)!;
      if (acc.parentId && accountMap.has(acc.parentId)) {
        const parent = accountMap.get(acc.parentId)!;
        parent.children.push(node);
        node.level = parent.level + 1;
      } else {
        rootAccounts.push(node);
      }
    });

    return rootAccounts;
  }

  /**
   * Get account balances
   */
  async getAccountBalances(tenantId: string): Promise<AccountBalanceResponse[]> {
    const accounts = await prisma.account.findMany({
      where: { tenantId, isActive: true },
    });

    return accounts.map((acc) => ({
      accountId: acc.id,
      accountCode: acc.code,
      accountName: acc.nameEn,
      accountNameAr: acc.nameAr,
      accountType: acc.accountType,
      balanceSYP: Number(acc.balanceSYP),
      balanceUSD: Number(acc.balanceUSD),
    }));
  }

  /**
   * Update account balance (called by journal entries)
   */
  async updateAccountBalance(accountId: string, amount: number, isDebit: boolean): Promise<void> {
    const account = await prisma.account.findUnique({
      where: { id: accountId },
    });

    if (!account) {
      throw new Error('Account not found');
    }

    const currentBalance = Number(account.balanceSYP);
    let newBalance = currentBalance;

    // Update balance based on account type and transaction type
    if (
      account.accountType === AccountType.ASSET ||
      account.accountType === AccountType.COGS ||
      account.accountType === AccountType.EXPENSE
    ) {
      // For assets and expenses: debit increases balance, credit decreases
      newBalance = isDebit ? currentBalance + amount : currentBalance - amount;
    } else {
      // For liabilities, equity, revenue: credit increases balance, debit decreases
      newBalance = isDebit ? currentBalance - amount : currentBalance + amount;
    }

    await prisma.account.update({
      where: { id: accountId },
      data: { balanceSYP: newBalance },
    });
  }

  /**
   * Helper: Check if targetId is a descendant of sourceId
   */
  private async isDescendant(sourceId: string, targetId: string): Promise<boolean> {
    let currentId = targetId;
    const maxDepth = 100; // Prevent infinite loops
    let depth = 0;

    while (currentId && depth < maxDepth) {
      if (currentId === sourceId) {
        return true;
      }

      const account = await prisma.account.findUnique({
        where: { id: currentId },
        select: { parentId: true },
      });

      if (!account || !account.parentId) {
        break;
      }

      currentId = account.parentId;
      depth++;
    }

    return false;
  }

  /**
   * Map Prisma account to Account response
   */
  private mapToAccountResponse(account: any): Account {
    return {
      id: account.id,
      tenantId: account.tenantId,
      code: account.code,
      nameAr: account.nameAr,
      nameEn: account.nameEn,
      parentId: account.parentId,
      accountType: account.accountType,
      balanceSYP: Number(account.balanceSYP),
      balanceUSD: Number(account.balanceUSD),
      isActive: account.isActive,
      createdAt: account.createdAt,
      updatedAt: account.updatedAt,
      children: account.children?.map((c: any) => this.mapToAccountResponse(c)),
      parent: account.parent ? this.mapToAccountResponse(account.parent) : undefined,
    };
  }
}