-- AlterTable
ALTER TABLE "CompanySettings" ADD COLUMN     "allowOnlineBooking" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "autoAssignTechnician" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "autoGenerateInvoiceNumber" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "companyAddress" TEXT,
ADD COLUMN     "companyLogoUrl" TEXT,
ADD COLUMN     "companyPhone" TEXT,
ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'USD',
ADD COLUMN     "dateFormat" TEXT NOT NULL DEFAULT 'DD/MM/YYYY',
ADD COLUMN     "defaultBookingDuration" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "invoiceFooterNote" TEXT,
ADD COLUMN     "invoicePrefix" TEXT NOT NULL DEFAULT 'INV',
ADD COLUMN     "loginBackgroundUrl" TEXT,
ADD COLUMN     "membershipAutoRenew" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "primaryColor" TEXT NOT NULL DEFAULT '#1976D2',
ADD COLUMN     "secondaryColor" TEXT NOT NULL DEFAULT '#FF5722',
ADD COLUMN     "sidebarStyle" TEXT NOT NULL DEFAULT 'LIGHT',
ADD COLUMN     "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 0.00,
ADD COLUMN     "timeFormat" TEXT NOT NULL DEFAULT '24h',
ADD COLUMN     "timezone" TEXT NOT NULL DEFAULT 'UTC',
ADD COLUMN     "whatsappBusinessNumber" TEXT;
