import { IJournalEntryRepository } from '../interfaces/IJournalEntryRepository';
import { IGRNRepository } from '../interfaces/IGRNRepository';
import { IAccountRepository } from '../interfaces/IAccountRepository';
import { v4 as uuidv4 } from 'uuid';

export class AutoJournalForGRNUseCase {
  constructor(
    private readonly journalEntryRepository: IJournalEntryRepository,
    private readonly grnRepository: IGRNRepository,
    private readonly accountRepository: IAccountRepository
  ) {}

  async execute(grnId: string): Promise<any> {
    // Get GRN
    const grn = await this.grnRepository.findById(grnId);
    if (!grn) {
      throw new Error('GRN not found');
    }

    // Check if journal entry already exists for this GRN
    const existingEntries = await this.journalEntryRepository.listByDateRange(
      new Date(0),
      new Date()
    );
    const existingEntry = existingEntries.find(
      (je: any) => je.reference === `GRN-${grnId}`
    );
    if (existingEntry) {
      return existingEntry; // Idempotent
    }

    // Get accounts
    const inventoryAccount = await this.accountRepository.findByCode('1000'); // Inventory
    const accountsPayableAccount = await this.accountRepository.findByCode('2000'); // AP
    const vatAccount = await this.accountRepository.findByCode('2200'); // VAT payable

    if (!inventoryAccount || !accountsPayableAccount || !vatAccount) {
      throw new Error('Required accounts not found in chart of accounts');
    }

    // Calculate total from GRN items
    const totalCost = grn.items?.reduce((sum: number, item: any) => sum + (item.quantity * item.unitPrice), 0) || 0;

    // Create journal entry lines
    const lines = [
      {
        id: uuidv4(),
        accountId: inventoryAccount.id,
        debit: totalCost,
        credit: 0,
        description: `Inventory received via GRN ${grnId}`,
      },
      {
        id: uuidv4(),
        accountId: accountsPayableAccount.id,
        debit: 0,
        credit: totalCost,
        description: `Supplier payable for GRN ${grnId}`,
      },
    ];

    // Create journal entry
    const journalEntry = {
      id: uuidv4(),
      date: grn.receivedDate,
      reference: `GRN-${grnId}`,
      lines,
      isPosted: true,
      isAutoGenerated: true,
      sourceId: grnId,
      sourceType: 'GRN',
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    return await this.journalEntryRepository.save(journalEntry);
  }
}
