import { IJournalEntryRepository } from '../interfaces/IJournalEntryRepository';
import { IStockMovementRepository } from '../interfaces/IStockMovementRepository';
import { IAccountRepository } from '../interfaces/IAccountRepository';
import { v4 as uuidv4 } from 'uuid';

export class AutoJournalForStockConsumptionUseCase {
  constructor(
    private readonly journalEntryRepository: IJournalEntryRepository,
    private readonly stockMovementRepository: IStockMovementRepository,
    private readonly accountRepository: IAccountRepository
  ) {}

  async execute(movementId: string): Promise<any> {
    // Get stock movement
    const movement = await this.stockMovementRepository.findById(movementId);
    if (!movement) {
      throw new Error('Stock movement not found');
    }

    // Only process OUT movements
    if (movement.type !== 'OUT') {
      throw new Error('Only OUT movements generate journal entries');
    }

    // Check if journal entry already exists for this movement
    const existingEntries = await this.journalEntryRepository.listByDateRange(
      new Date(0),
      new Date()
    );
    const existingEntry = existingEntries.find(
      (je: any) => je.reference === `STK-${movementId}`
    );
    if (existingEntry) {
      return existingEntry; // Idempotent
    }

    // Get accounts
    const inventoryAccount = await this.accountRepository.findByCode('1000'); // Inventory
    const costOfGoodsSoldAccount = await this.accountRepository.findByCode('5000'); // COGS

    if (!inventoryAccount || !costOfGoodsSoldAccount) {
      throw new Error('Required accounts not found in chart of accounts');
    }

    // Calculate cost
    const totalCost = movement.quantity * movement.costSYP;

    // Create journal entry lines
    const lines = [
      {
        id: uuidv4(),
        accountId: costOfGoodsSoldAccount.id,
        debit: totalCost,
        credit: 0,
        description: `COGS for stock consumption ${movementId}`,
      },
      {
        id: uuidv4(),
        accountId: inventoryAccount.id,
        debit: 0,
        credit: totalCost,
        description: `Inventory reduction for stock consumption ${movementId}`,
      },
    ];

    // Create journal entry
    const journalEntry = {
      id: uuidv4(),
      date: movement.createdAt,
      reference: `STK-${movementId}`,
      lines,
      isPosted: true,
      isAutoGenerated: true,
      sourceId: movementId,
      sourceType: 'STOCK_CONSUMPTION',
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    return await this.journalEntryRepository.save(journalEntry);
  }
}
