import { IJournalEntryRepository } from '../interfaces/IJournalEntryRepository';
import { IPaymentRepository } from '../interfaces/IPaymentRepository';
import { IAccountRepository } from '../interfaces/IAccountRepository';
import { v4 as uuidv4 } from 'uuid';

export class AutoJournalForCustomerPaymentUseCase {
  constructor(
    private readonly journalEntryRepository: IJournalEntryRepository,
    private readonly paymentRepository: IPaymentRepository,
    private readonly accountRepository: IAccountRepository
  ) {}

  async execute(paymentId: string): Promise<any> {
    // Get payment
    const payment = await this.paymentRepository.findById(paymentId);
    if (!payment) {
      throw new Error('Payment not found');
    }

    // Check if journal entry already exists for this payment
    const existingEntries = await this.journalEntryRepository.listByDateRange(
      new Date(0),
      new Date()
    );
    const existingEntry = existingEntries.find(
      (je: any) => je.reference === `PAY-${paymentId}`
    );
    if (existingEntry) {
      return existingEntry; // Idempotent
    }

    // Get accounts
    const cashAccount = await this.accountRepository.findByCode('1100'); // Cash/Bank
    const accountsReceivableAccount = await this.accountRepository.findByCode('1200'); // AR

    if (!cashAccount || !accountsReceivableAccount) {
      throw new Error('Required accounts not found in chart of accounts');
    }

    // Create journal entry lines
    const lines = [
      {
        id: uuidv4(),
        accountId: cashAccount.id,
        debit: payment.amount,
        credit: 0,
        description: `Customer payment ${paymentId}`,
      },
      {
        id: uuidv4(),
        accountId: accountsReceivableAccount.id,
        debit: 0,
        credit: payment.amount,
        description: `AR reduction for customer payment ${paymentId}`,
      },
    ];

    // Create journal entry
    const journalEntry = {
      id: uuidv4(),
      date: payment.date,
      reference: `PAY-${paymentId}`,
      lines,
      isPosted: true,
      isAutoGenerated: true,
      sourceId: paymentId,
      sourceType: 'CUSTOMER_PAYMENT',
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    return await this.journalEntryRepository.save(journalEntry);
  }
}
