import { IJournalEntryRepository } from '../interfaces/IJournalEntryRepository';
import { IInvoiceRepository } from '../interfaces/IInvoiceRepository';
import { IAccountRepository } from '../interfaces/IAccountRepository';
import { v4 as uuidv4 } from 'uuid';

export class AutoJournalForInvoiceUseCase {
  constructor(
    private readonly journalEntryRepository: IJournalEntryRepository,
    private readonly invoiceRepository: IInvoiceRepository,
    private readonly accountRepository: IAccountRepository
  ) {}

  async execute(invoiceId: string): Promise<any> {
    // Get invoice
    const invoice = await this.invoiceRepository.findById(invoiceId);
    if (!invoice) {
      throw new Error('Invoice not found');
    }

    // Check if journal entry already exists for this invoice
    const existingEntries = await this.journalEntryRepository.listByDateRange(
      new Date(0),
      new Date()
    );
    const existingEntry = existingEntries.find(
      (je: any) => je.reference === `INV-${invoiceId}`
    );
    if (existingEntry) {
      return existingEntry; // Idempotent - return existing entry
    }

    // Get accounts
    const accountsReceivableAccount = await this.accountRepository.findByCode('1200'); // AR account
    const revenueAccount = await this.accountRepository.findByCode('4000'); // Revenue account
    const vatAccount = await this.accountRepository.findByCode('2200'); // VAT payable

    if (!accountsReceivableAccount || !revenueAccount || !vatAccount) {
      throw new Error('Required accounts not found in chart of accounts');
    }

    // Create journal entry lines
    const lines = [
      {
        id: uuidv4(),
        accountId: accountsReceivableAccount.id,
        debit: invoice.total,
        credit: 0,
        description: `Invoice ${invoiceId}`,
      },
      {
        id: uuidv4(),
        accountId: revenueAccount.id,
        debit: 0,
        credit: invoice.subtotal,
        description: `Service revenue for invoice ${invoiceId}`,
      },
      {
        id: uuidv4(),
        accountId: vatAccount.id,
        debit: 0,
        credit: invoice.tax,
        description: `VAT for invoice ${invoiceId}`,
      },
    ];

    // Create journal entry
    const journalEntry = {
      id: uuidv4(),
      date: invoice.createdAt,
      reference: `INV-${invoiceId}`,
      lines,
      isPosted: true,
      isAutoGenerated: true,
      sourceId: invoiceId,
      sourceType: 'INVOICE',
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    return await this.journalEntryRepository.save(journalEntry);
  }
}
