/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx,js,jsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: "#E31E24",
        "primary-container": "#B91C1C",
        "primary-fixed": "#FEE2E2",
        "primary-fixed-dim": "#FECACA",
        "on-primary": "#ffffff",
        "on-primary-container": "#FECACA",
        "on-primary-fixed": "#450A0A",
        "on-primary-fixed-variant": "#991B1B",
        secondary: "#000000",
        "secondary-container": "#1A1A1A",
        "secondary-fixed": "#E5E5E5",
        "secondary-fixed-dim": "#CCCCCC",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#F5F5F5",
        "on-secondary-fixed": "#0A0A0A",
        "on-secondary-fixed-variant": "#333333",
        tertiary: "#7C2D12",
        "tertiary-container": "#9C2E02",
        "tertiary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#ffb59e",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffb9a4",
        "on-tertiary-fixed": "#3a0b00",
        "on-tertiary-fixed-variant": "#842500",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        background: "#ffffff",
        "on-background": "#000000",
        surface: "#ffffff",
        "surface-dim": "#E5E5E5",
        "surface-bright": "#ffffff",
        "surface-variant": "#F5F5F5",
        "surface-subtle": "#FAFAFA",
        "surface-contrast": "#F0F0F0",
        "surface-container": "#F8F8F8",
        "surface-container-low": "#FCFCFC",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#F2F2F2",
        "surface-container-highest": "#EDEDED",
        "on-surface": "#000000",
        "on-surface-variant": "#333333",
        "inverse-surface": "#1A1A1A",
        "inverse-on-surface": "#F5F5F5",
        "inverse-primary": "#FECACA",
        outline: "#737685",
        "outline-variant": "#D4D4D4",
        "surface-tint": "#E31E24",
        "bg-main": "#ffffff",
        "glass-bg": "rgba(255, 255, 255, 0.85)",
        "glass-border": "rgba(255, 255, 255, 0.6)",
        "primary-glow": "rgba(227, 30, 36, 0.5)",
        "secondary-light": "#E5E5E5",
        border: "#E5E5E5",
        "text-secondary": "#333333",
        "text-tertiary": "#666666",
        warning: "#D97706",
        info: "#0891B2",
        "accounting-tint": "#FEF2F2",
        "hr-tint": "#F5F5F5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "280px",
        "sidebar-mini": "72px",
        "header-height": "64px",
        "container-margin": "24px",
        "sidebar-offset": "16px",
        "card-padding": "24px",
        gutter: "20px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      fontFamily: {
        beVietnamPro: ["Be Vietnam Pro", "sans-serif"],
        ibmPlexSans: ["IBM Plex Sans Arabic", "IBM Plex Sans", "sans-serif"],
        jetbrainsMono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["13px", { lineHeight: "1", fontWeight: "600" }],
        "label-mono": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "financial-data": ["15px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
