/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx,js,jsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: "#003594",
        "primary-container": "#004ac6",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#b8c8ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        secondary: "#712ae2",
        "secondary-container": "#8b4bfc",
        "secondary-fixed": "#eaddff",
        "secondary-fixed-dim": "#d2bbff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "on-secondary-fixed": "#25005a",
        "on-secondary-fixed-variant": "#5a00c6",
        tertiary: "#751f00",
        "tertiary-container": "#9c2e02",
        "tertiary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#ffb59e",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffb9a4",
        "on-tertiary-fixed": "#3a0b00",
        "on-tertiary-fixed-variant": "#842500",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        background: "#faf8ff",
        "on-background": "#191b23",
        surface: "#faf8ff",
        "surface-dim": "#d9d9e4",
        "surface-bright": "#faf8ff",
        "surface-variant": "#e2e2ec",
        "surface-subtle": "#F8FAFC",
        "surface-contrast": "#F1F5F9",
        "surface-container": "#ededf8",
        "surface-container-low": "#f3f3fd",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e7f2",
        "surface-container-highest": "#e2e2ec",
        "on-surface": "#191b23",
        "on-surface-variant": "#434654",
        "inverse-surface": "#2e3038",
        "inverse-on-surface": "#f0f0fb",
        "inverse-primary": "#b4c5ff",
        outline: "#737685",
        "outline-variant": "#c3c6d6",
        "surface-tint": "#1b55d0",
        "bg-main": "#fcfcff",
        "glass-bg": "rgba(255, 255, 255, 0.7)",
        "glass-border": "rgba(255, 255, 255, 0.4)",
        "primary-glow": "rgba(0, 74, 198, 0.5)",
        "secondary-light": "#ede9fe",
        border: "#E2E8F0",
        "text-secondary": "#475569",
        "text-tertiary": "#94A3B8",
        warning: "#D97706",
        info: "#0891B2",
        "accounting-tint": "#EFF6FF",
        "hr-tint": "#F5F3FF",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "280px",
        "sidebar-mini": "72px",
        "header-height": "64px",
        "container-margin": "24px",
        "sidebar-offset": "16px",
        "card-padding": "24px",
        gutter: "20px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      fontFamily: {
        beVietnamPro: ["Be Vietnam Pro", "sans-serif"],
        ibmPlexSans: ["IBM Plex Sans Arabic", "IBM Plex Sans", "sans-serif"],
        jetbrainsMono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["13px", { lineHeight: "1", fontWeight: "600" }],
        "label-mono": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "financial-data": ["15px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
